

#security.user.name: richard
#security.user.password: password
#security.user.role: USER


#security:
#  oauth2:
#    client:
#      clientId: admin
#      clientSecret: admin 
#      access-token-validity-seconds:30
#      refresh-token-validity-seconds:300
#      authorized-grant-types: authorization_code,refresh_token,password
#      scope:toll_read,toll_report



server:
  port: 9055
  servlet:
    context-path: /auth
    
user:
  oauth:
    clientId: R2dpxQ3vPrtfgF72
    clientSecret: fDw7Mpkk5czHNuSRtmhGmAGL42CaxQB9
    redirectUris: http://localhost:9050/login/oauth2/code/local

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/authorizationschema?useSSL=false
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
                format_sql: true
        hibernate:
            ddl-auto: update
        show-sql: true
        generate-ddl: false
  